sonar.projectKey=exsecrabilis_lab_1c_dfecd521-486e-48f5-8cf2-88e215400c18
sonar.qualitygate.wait=true
sonar.projectName=lab_1c
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/bin/**,**/temp/**,**/*.md,**/*.png,**/*.jpg,**/*.pdf
sonar.sources=./src
sonar.tests=./tests

sonar.inclusions=**/*.bsl, **/*.os



