@startuml Test2
' Диаграмма активности
start
:Обработка входящего запроса;

if (Определенное условие) then (Да)
    
    :Дать посмотреть коллеге;

    if (Удалось получить расшифровку?) then (Да) 
    else (Нет)
        :Рисуем диаграмму;
    endif
    :Завершаем оценку //Решением//;
else (Нет)
    stop
endif
stop

@enduml