@startuml
'Диаграмма последовательности

' Изменение внешнего вида https://github.com/Drakemor/RedDress-PlantUML
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
' Автонумерация стрелок
autonumber

'Отключаем нижний повтор объектов
skinparam style strictuml

' Параметры
actor Сотрудник #red
control 1ССкрипт as "OneScript"
control СКЛПродуктив as "SQL-продуктив" #Black
database БазаИсточник as "База рабочая" #Black
database Шара
control СКЛТестовый as "SQL-тестовый" #Green
database БазаПриемник as "База приемник-тест" #Green

'Диаграмма
Сотрудник -> 1ССкрипт: Вызывает команду перезаливки\n базы на тест сервере 1С
1ССкрипт --> Сотрудник: Информирует о ходе выполнения процесса
1ССкрипт -> СКЛПродуктив: Вызов запроса\nдля выполнения бэкапа рабочей базы\n по ADO (права backupoperator)
СКЛПродуктив -> БазаИсточник: Выполнение бэкапа базы
СКЛПродуктив -> Шара: Размещение бэкапа\n на временной шаре для другого SQL
1ССкрипт -> СКЛТестовый: Вызов команды восстановления бэкапа по ADO
СКЛТестовый -> БазаПриемник: Восстановление бэкапа из Шары в базу

@enduml