@startuml
'Диаграмма последовательности

' Изменение внешнего вида https://github.com/Drakemor/RedDress-PlantUML
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
' Автонумерация стрелок
autonumber

'Отключаем нижний повтор объектов
skinparam style strictuml

' Параметры
actor Сотрудник #red
control АлкоТестер
database ЗУП as "1С ЗУП"
actor Руководители #Black

'Диаграмма
Сотрудник -> АлкоТестер: Проходит алкорамку
АлкоТестер --> Сотрудник: Превышение допустимого показателя
АлкоТестер -> ЗУП: Фиксация значения о превышении
alt Сценарий 1. Сотрудник повторно проходит алкорамку
    ...< 10 minutes latter...
    Сотрудник -> АлкоТестер: Проходит алкорамку повторно
    'note left: Сценарий 1
    АлкоТестер --> Сотрудник: Превышение допустимого показателя
    АлкоТестер -> ЗУП: Фиксация значения о превышении
    ЗУП -> Руководители: Уведомление по email
    note right: Произошло повторное превышение\nдопустимого значения  Алкотестера
else Сценарий 2. Сотрудник отказался от прохождения повторно алкорамки
    ...> 10 minutes latter...
    ЗУП -> Руководители: Уведомление по email
    note right: Произошло повторное превышение\nдопустимого значения  Алкотестера.\nСотрудник не проходил повторно через алкотестер
end

@enduml