@startuml

'Диаграмма состояний
[*] --> Процесс1: исходные данные
Процесс1 --> ПроектДанных: данные процесса
Процесс1 --> Проект: не актуальные данные
Процесс1 --> Проект3: не актуальные данные
Проект3 --> [*]
Проект --> [*]
ПроектДанных-->[*]

@enduml